### ISSUE TITLE
Throws an exception on parsing some AIFF files

### ISSUE THREAD

**Issue by Borewit** [Borewit/music-metadata#144]
**Bug description**
Throws an exception on some AIFF files.

Parsing: [AFsp/M1F1-AlawC-AFsp.aif](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Samples/AFsp/M1F1-AlawC-AFsp.aif)

**Cause**
Current implementation is missing the following:

> ckData contains the data stored in the chunk. The format of this data is determined by ckID. If
the data is an odd number of bytes in length, a zero pad byte must be added at the end

- [x] Fix padding
- [x] FIx bit-rate calculation
- [x] `format.lossless` indicator

**Comment by Borewit** [comment]
Fixed in [v2.8.1](https://github.com/Borewit/music-metadata/releases/tag/v2.8.1)

**Comment by raikusy** [comment]
This issue still persist.

`Error message: FourCC contains invalid characters: 28 63 29 20.`

For aiff files. [Example](https://rr-s3.ovechr.com/local/audio/aiff/05c5e92e-2c8a-4954-85c0-fe0ca1385254_09_-_No_Sanctuary_Here.aiff)

**Comment by Borewit** [comment]
> This issue still persist.

Despite the generic title, this issue appeared to be related to handling  odd number of bytes in length, which has been fixed. I will investigate your issue (#643).
